[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "spyparser"
version = "0.1.0"
description = "simple python parser for natural lanuage"
requires-python = ">=3.11"

[project.scripts]
spyparser = "spyparser.cli:main"

